main: gg.Main
name: GunGame
version: 1.0.0
description: demo pvp plugin
commands:
    join:
        description: joins arena
        usage: /<command> [id]
    create:
        description: creates arena
        usage: /<command>
    remove:
        description: removes arena
        usage: /<command> [id]
    leave:
        description: leaves arena
        usage: /<command>