name: JusJusAlias
author: jusjus112
version: 1.3.1
main: jusjus112.topia.SudoAlias

commands:
  sudoalias:
    description: SudoAlias management command
    aliases: [sa]
    usage: Syntax Error! /<command> help